name: Wolox

on:
  push:
    branches: [ fr-1-deploy ]
  pull_request:
    branches: [ fr-1-deploy ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v1.4.3

    - name: NPM installation
      run: npm i -f

    - name: Build
      run: npm build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: 60f456a797b1333a505303f8f17e3235bc9b373d
        publish_dir: ./dist/wolox
        publish_branch: fr-1-deploy
        external_repository: rochafederico/rochafederico.github.io
